version: '3'

services:
  node-app:
    container_name: express-node-app-container
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - node-app

  # Uncomment these services if you want to use MongoDB
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo-db-container
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongo-db:/data/db

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express-container
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #   depends_on:
  #     - mongo

volumes:
  postgres-db:
  # mongo-db:
