version: "3.9"

services:
  node-app:
    image: your-dockerhub-username/express-app:latest  # Replace with your actual image
    ports:
      - "4000:4000"
    env_file:
      - .env
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-db:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  redis:
    image: redis:latest
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - node-app
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-network

volumes:
  postgres-db:

networks:
  app-network:
    driver: overlay
